sudo: required

services: 
    - docker

before_install:
    - docker build -t ahatajon/react-test -f ./client/Dockerfile.dev  ./client

script:
    - docker run -e CI=true ahatajon/react-test npm test 

after_success:
    - docker build -t ahatajon/multi-client ./client
    - docker build -t ahatajon/multi-nginx ./nginx
    - docker build -t ahatajon/multi-server ./server
    - docker build -t ahatajon/multi-worker ./worker

    # login to the docekr CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take images and push them to the docker hub
    - docker push ahatajon/multi-client
    - docker push ahatajon/multi-nginx
    - docker push ahatajon/multi-server
    - docker push ahatajon/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: complex
    env: Complex-env 
    bucket_name: elasticbeanstalk-us-east-1-014588499640
    bucket_path: complex
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    
    